project-name: Awsv4sig
project-version:
  minor: 0
  major: 0
  patch: 1
build-type: executable-library
maintainer: 'Łukasz lol'
synopsis: 'Cmon it\'s a playground'
author: 'Miron Markowski'
license:
  tag: none
description: 'Just for fun'
